### PR TITLE
Add xenial to geckofx

### PR DESCRIPTION
**Pull request by marksvc**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/ci-builder-scripts/3)

### CODE REVIEW

**Comment by ermshiperete** [comment]
See inline comment; otherwise LGTM



---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[groovy/geckofx_jobs.groovy, line 7 [r1]](https://reviewable.io:443/reviews/sillsdev/ci-builder-scripts/3#-K1YLS13CkEiRr4o0DIt)** ([raw file](https://github.com/sillsdev/ci-builder-scripts/blob/4c37db7dbbdefd9396a17add5974bcd1850c2df3/groovy/geckofx_jobs.groovy#L7)):</sup>
what about adding wily as well (and possibly remove utopic)?



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/ci-builder-scripts/3)

**Comment by marksvc** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[groovy/geckofx_jobs.groovy, line 7 [r1]](https://reviewable.io:443/reviews/sillsdev/ci-builder-scripts/3#-K1YLS13CkEiRr4o0DIt)** ([raw file](https://github.com/sillsdev/ci-builder-scripts/blob/4c37db7dbbdefd9396a17add5974bcd1850c2df3/groovy/geckofx_jobs.groovy#L7)):</sup>
Done.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/ci-builder-scripts/3)

**Comment by ermshiperete** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/ci-builder-scripts/3)

**Comment by ermshiperete** [comment]
:-1:  Sorry, just notice now: This change should go through Gerrit, otherwise it'll be lost.



---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/ci-builder-scripts/3)

**Pull request closed without merging**
